name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: ./app
    - run: npm run build --if-present
      working-directory: ./app
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag zalmane/basin:$(date +%s) -t zalmane/basin:latest .

