name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: ./app
    - run: npm run build --if-present
      working-directory: ./app

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: zalmane
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        repository: zalmane/basin
        tags: latest
